[package]
name = "dms_try1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3.0"